export let rows = [
    {
        id: 1,
        product: "HTML Book",
        customer: "Hamada",
        date: "1 March",
        amount: 25,
        method: "cash",
        status: "Approved",
    },
    {
        id: 2,
        product: "CSS Book",
        customer: "Mohamed",
        date: "18 Jun",
        amount: 20,
        method: "cash",
        status: "Approved",
    },
    {
        id: 3,
        product: "JS Book",
        customer: "Ali",
        date: "1 Feb",
        amount: 15,
        method: "Del",
        status: "Pendding",
    },
    {
        id: 4,
        product: "JS Book",
        customer: "Sayed",
        date: "25 Jun",
        amount: 29,
        method: "cash",
        status: "Approved",
    },
    {
        id: 5,
        product: "React Book",
        customer: "Mossad",
        date: "1 march",
        amount: 60,
        method: "cash",
        status: "Pendding",
    },
    {
        id: 6,
        product: "Bootstrap Book",
        customer: "Hamada",
        date: "1 April",
        amount: 25,
        method: "Del",
        status: "Pendding",
    },
    {
        id: 7,
        product: "Angular Book",
        customer: "Saad",
        date: "8 Sub",
        amount: 8,
        method: "Del",
        status: "Approved",
    },
    {
        id: 8,
        product: "Django Book",
        customer: "Hamada",
        date: "2 Feb",
        amount: 32,
        method: "Del",
        status: "Approved",
    },
    {
        id: 9,
        product: "React Book",
        customer: "Hamada",
        date: "3 Jun",
        amount: 22,
        method: "Del",
        status: "Pendding",
    },
    {
        id: 10,
        product: "Vue Book",
        customer: "Mohssen",
        date: "1 April",
        amount: 18,
        method: "Del",
        status: "Approved",
    },
    {
        id: 11,
        product: "JS Book",
        customer: "Hamada",
        date: "1 may",
        amount: 20,
        method: "Del",
        status: "Pendding",
    },
    {
        id: 12,
        product: "Python Book",
        customer: "Hassan",
        date: "25 April",
        amount: 10,
        method: "Del",
        status: "Approved",
    },
]


export let columns = [
    { field: 'id', headerName: 'ID', width: 70 },
    {
        field: "product",
        headerName: "Product",
        width: 180,
    },
    {
        field: "customer",
        headerName: "Customer",
        width: 180
    },
    {
        field: "date",
        headerName: "Date",
        width: 150
    },
    {
        field: "amount",
        headerName: "Amount",
        width: 150,
    },
    {
        field: "method",
        headerName: "Method",
        width: 150,
    },
    {
        field: "status",
        headerName: "Status",
        width: 150,
    },
]